repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace

- repo: https://github.com/qiaojunfeng/pre-commit-julia-format
  rev: v0.2.0
  hooks:
  - id: julia-format
