name = "RQADeforestation"
uuid = "3f1d9318-18cc-4ffd-9937-04025ce33b74"
authors = ["Daniel Loos <dloos@bgc-jena.mpg.de> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
