name: Build binaries and docker images
on:
  push:
    branches:
      - main
    tags: ["*"]
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push compiler docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: "{{defaultContext}}:packagecompiler"
          file: Dockerfile
          tags: danlooo/julia_package_compiler_dev:latest
          cache-from: type=registry,ref=danlooo/julia_package_compiler_dev:cache
          cache-to: type=registry,ref=danlooo/julia_package_compiler_dev:cache,mode=max

      - name: Run compiler docker container
        run: >
          sudo chown -R $USER:$USER . &&
          docker pull danlooo/julia_package_compiler_dev:latest &&
          docker run -v $PWD:/work danlooo/julia_package_compiler_dev:latest /work &&
          sudo chown -R $USER:$USER .

      - name: Build and push binary docker image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: .
          file: Dockerfile
          tags: danlooo/rqa_deforestation:latest, danlooo/rqa_deforestation:${{ github.sha }}
          cache-from: type=registry,ref=danlooo/julia_package_compiler_dev:cache
          cache-to: type=registry,ref=danlooo/julia_package_compiler_dev:cache,mode=max

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: packagecompiler/app
