name: PackageCompiler
on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:
jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          context: "{{defaultContext}}:packagecompiler"
          file: Dockerfile
          tags: danlooo/julia_package_compiler_dev:latest
          cache-from: type=registry,ref=danlooo/julia_package_compiler_dev:cache
          cache-to: type=registry,ref=danlooo/julia_package_compiler_dev:cache,mode=max

      - name: Run Docker container
        run: docker run -v $PWD:/work danlooo/julia_package_compiler_dev:latest /work

      - name: Upload binaries
        uses: actions/upload-artifact@v4
        with:
          name: binaries
          path: packagecompiler/app
