name: PackageCompiler
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}:packagecompiler"
          file: PackageCompiler.Dockerfile
          tags: danlooo/julia_package_compiler_dev:latest
          cache-from: type=registry,ref=danlooo/julia_package_compiler_dev:cache
          cache-to: type=registry,ref=danlooo/julia_package_compiler_dev:cache,mode=max

      - name: Run Docker container
        run: docker run danlooo/julia_package_compiler_dev:latest
